// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rdmvowapniaadgbktrjg.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbXZvd2FwbmlhYWRnYmt0cmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0Mzk4NzIsImV4cCI6MjA0NzAxNTg3Mn0.UBRgCIXLS6L39FJBr8rowZwsO_6mGE1bTLRaJLRKFUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);